import { Platform, StyleSheet } from 'react-native';

const createAppStyles = ({ TYPO_SCALE, LETTER_SPACING, FONT_HEADING, FONT_BODY, theme }) => {
  const colors = theme?.colors || {};
  const rgba = theme?.rgba || {};
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.appBackground,
    },
    scroll: {
      paddingBottom: 64,
    },
    scrollCompact: {
      paddingHorizontal: 16,
    },
    footerCredits: {
      marginTop: 20,
      marginBottom: 12,
      alignItems: 'center',
      opacity: 0.55,
    },
    footerCreditsText: {
      fontFamily: FONT_BODY,
      fontSize: TYPO_SCALE.small,
      color: colors.textMuted,
      letterSpacing: LETTER_SPACING.body,
      textAlign: 'center',
    },
    header: {
      backgroundColor: colors.headerBackground,
      borderRadius: 22,
      borderWidth: 2,
      borderColor: colors.accent,
      paddingVertical: 12,
      paddingHorizontal: 16,
      margin: 16,
      overflow: 'hidden',
    },
    headerTopRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 72,
    },
    headerText: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerLogo: {
      width: 220,
      height: 48,
      alignSelf: 'center',
      transform: [{ scale: 3 }],
    },
    patternOverlay: {
      position: 'absolute',
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      opacity: 0.15,
    },
    patternDot: {
      position: 'absolute',
      backgroundColor: colors.accent,
      borderRadius: 50,
    },
    patternLine: {
      position: 'absolute',
      backgroundColor: colors.accent,
      borderRadius: 50,
    },
    splashContainer: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.appBackground,
    },
    splashGlow: {
      width: 240,
      height: 240,
      borderRadius: 120,
      backgroundColor: rgba.accentGlow,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 24,
    },
    splashLogo: {
      width: 180,
      height: 180,
    },
    splashText: {
      color: colors.text,
      fontFamily: FONT_BODY,
      fontSize: TYPO_SCALE.body,
    },
    dropdownOverlay: {
      flex: 1,
      backgroundColor: rgba.overlay,
      justifyContent: 'center',
      padding: 24,
    },
    creationModal: {
      backgroundColor: colors.surface,
      borderRadius: 18,
      borderWidth: 2,
      borderColor: colors.accent,
      padding: 18,
      width: '100%',
      maxWidth: 520,
      alignSelf: 'center',
    },
    dropdownPanelTitle: {
      color: colors.text,
      fontFamily: FONT_HEADING,
      fontSize: TYPO_SCALE.subheading,
      letterSpacing: LETTER_SPACING.heading,
      marginBottom: 12,
    },
    creationInput: {
      backgroundColor: colors.surfaceAlt5,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.borderStrong,
      color: colors.text,
      paddingHorizontal: 12,
      paddingVertical: 8,
      fontFamily: FONT_BODY,
      fontSize: TYPO_SCALE.body,
    },
    creationActions: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      marginTop: 16,
      gap: 12,
      flexWrap: 'wrap',
    },
    creationButton: {
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 10,
      borderWidth: 1,
      flexGrow: 1,
      flexBasis: 140,
      minWidth: 120,
      maxWidth: '100%',
    },
    creationButtonPrimary: {
      backgroundColor: colors.accent,
      borderColor: colors.accent,
    },
    creationButtonSecondary: {
      borderColor: colors.borderSubtle,
    },
    creationButtonText: {
      fontFamily: FONT_BODY,
      color: colors.textSoft,
      fontSize: TYPO_SCALE.body,
      flexShrink: 1,
      flexWrap: 'wrap',
      textAlign: 'center',
    },
    creationButtonTextPrimary: {
      color: colors.textOnAccent,
    },
    confirmMessage: {
      color: colors.textSoft,
      fontFamily: FONT_BODY,
      fontSize: TYPO_SCALE.body,
      marginBottom: 12,
    },
    searchModal: {
      backgroundColor: colors.surface,
      borderRadius: 16,
      borderColor: colors.accent,
      borderWidth: 2,
      padding: 16,
      width: '100%',
      maxWidth: 560,
      alignSelf: 'center',
    },
    searchType: {
      color: colors.textMuted,
      fontSize: TYPO_SCALE.small,
      fontFamily: FONT_BODY,
    },
    searchResultRow: {
      paddingVertical: 8,
      borderBottomWidth: 1,
      borderBottomColor: rgba.divider,
    },
    searchResultName: {
      color: colors.text,
      fontFamily: FONT_BODY,
      fontSize: TYPO_SCALE.body,
    },
    contextBar: {
      margin: 16,
      padding: 16,
      borderRadius: 18,
      borderWidth: 2,
      borderColor: colors.accent,
      backgroundColor: colors.surface,
      gap: 10,
    },
    licenseBanner: {
      marginHorizontal: 16,
      marginTop: 12,
      paddingVertical: 10,
      paddingHorizontal: 14,
      borderRadius: 14,
      borderWidth: 2,
      borderColor: colors.borderStrong,
      backgroundColor: colors.surfaceAlt2,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    licenseBannerActive: {
      borderColor: colors.borderSubtle,
      backgroundColor: colors.surfaceAlt3,
    },
    licenseBannerGrace: {
      borderColor: colors.warning || colors.accent,
      backgroundColor: colors.surfaceAlt4,
    },
    licenseBannerExpired: {
      borderColor: colors.danger || colors.accent,
      backgroundColor: colors.surfaceAlt5,
    },
    licenseBannerText: {
      flex: 1,
      color: colors.text,
      fontFamily: FONT_BODY,
      fontSize: TYPO_SCALE.body,
      letterSpacing: LETTER_SPACING.body,
    },
    licenseBannerCta: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.borderStrong,
      backgroundColor: colors.surfaceAlt2,
    },
    licenseBannerCtaText: {
      color: colors.text,
      fontFamily: FONT_BODY,
      fontSize: TYPO_SCALE.small,
      letterSpacing: LETTER_SPACING.body,
    },
    licenseModal: {
      backgroundColor: colors.surface,
      borderRadius: 18,
      borderWidth: 2,
      borderColor: colors.accent,
      padding: 18,
      gap: 12,
      width: '100%',
      maxWidth: 560,
      alignSelf: 'center',
    },
    modalBackdrop: {
      position: 'absolute',
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    licenseMockRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginTop: 4,
    },
    licenseNote: {
      color: colors.textMuted,
      fontFamily: FONT_BODY,
      fontSize: TYPO_SCALE.small,
    },
    contextBarCompact: {
      marginHorizontal: 12,
    },
    contextHeading: {
      color: colors.text,
      fontFamily: FONT_HEADING,
      fontSize: TYPO_SCALE.subheading,
      letterSpacing: LETTER_SPACING.heading,
    },
    contextSub: {
      color: colors.textMuted,
      fontFamily: FONT_BODY,
      fontSize: TYPO_SCALE.body,
    },
    contextSelectors: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 14,
    },
    contextSelectorsCompact: {
      gap: 10,
    },
    selectorBlock: {
      flex: 1,
      minWidth: 260,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      padding: 12,
      gap: 10,
      backgroundColor: colors.surfaceAlt,
    },
    selectorBlockFull: {
      width: '100%',
    },
    selectorUtility: {
      backgroundColor: colors.surfaceAlt4,
    },
    selectorUtilityCompact: {
      paddingHorizontal: 10,
    },
    entityActions: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    entityActionBtn: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 10,
      paddingHorizontal: 10,
      paddingVertical: 6,
      backgroundColor: colors.surfaceAlt3,
      flexGrow: 1,
      flexBasis: 220,
      maxWidth: '100%',
    },
    entityActionText: {
      color: colors.text,
      fontFamily: FONT_HEADING,
      fontSize: TYPO_SCALE.body,
      letterSpacing: LETTER_SPACING.heading,
      flexShrink: 1,
      flexWrap: 'wrap',
    },
    inputLabel: {
      color: colors.textMuted,
      fontFamily: FONT_BODY,
      fontSize: TYPO_SCALE.body,
    },
    logEmpty: {
      color: colors.textMuted,
      fontFamily: FONT_BODY,
      fontSize: TYPO_SCALE.body,
    },
    card: {
      marginHorizontal: 16,
      marginTop: 16,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      overflow: 'hidden',
    },
    cardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 14,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    cardIconWrap: {
      width: 88,
      height: 88,
      borderRadius: 18,
      borderWidth: 2,
      borderColor: colors.accent,
      backgroundColor: colors.surfaceAlt,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 14,
    },
    cardIcon: {
      width: 64,
      height: 64,
    },
    cardHeaderText: {
      flex: 1,
      gap: 4,
    },
    cardTitle: {
      color: colors.text,
      fontFamily: FONT_HEADING,
      fontSize: TYPO_SCALE.subheading,
      letterSpacing: LETTER_SPACING.heading,
    },
    cardSubtitle: {
      color: colors.textMuted,
      fontFamily: FONT_BODY,
      fontSize: TYPO_SCALE.body,
    },
    cardToggle: {
      fontFamily: FONT_HEADING,
      color: colors.accent,
      fontSize: TYPO_SCALE.subheading,
    },
    cardBody: {
      padding: 16,
      gap: 12,
    },
    cardBodyReadOnly: {
      opacity: 0.7,
    },
    helperText: {
      color: colors.textMuted,
      fontFamily: FONT_BODY,
      fontSize: TYPO_SCALE.body,
      marginBottom: 6,
    },
    helperTextCompact: {
      color: colors.textMuted,
      fontFamily: FONT_BODY,
      fontSize: TYPO_SCALE.body,
      marginBottom: 2,
    },
    logSection: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      padding: 10,
      gap: 8,
    },
    logSectionLux: {
      backgroundColor: colors.surfaceAlt4,
      borderColor: colors.info || colors.accent,
    },
    logSectionT: {
      backgroundColor: colors.surfaceAlt3,
      borderColor: colors.warning || colors.accent,
    },
    logSectionLabel: {
      color: colors.text,
      fontFamily: FONT_HEADING,
      fontSize: TYPO_SCALE.body,
      letterSpacing: LETTER_SPACING.heading,
    },
    advancedToggle: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 8,
      backgroundColor: colors.surfaceAlt,
    },
    advancedToggleText: {
      color: colors.text,
      fontFamily: FONT_HEADING,
      fontSize: TYPO_SCALE.body,
      letterSpacing: LETTER_SPACING.heading,
    },
    advancedToggleIcon: {
      color: colors.accent,
      fontFamily: FONT_HEADING,
      fontSize: TYPO_SCALE.body,
    },
    advancedPanel: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      padding: 12,
      backgroundColor: colors.surfaceAlt,
      gap: 10,
    },
    textInput: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 8,
      color: colors.text,
      backgroundColor: colors.surfaceAlt2,
      fontFamily: FONT_BODY,
      fontSize: TYPO_SCALE.body,
    },
    textInputCompact: {
      paddingVertical: 6,
    },
    rowSplit: {
      flexDirection: 'row',
      gap: 10,
      flexWrap: 'wrap',
    },
    ghostButton: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 8,
      backgroundColor: colors.surfaceAlt3,
      flexGrow: 1,
      flexBasis: 220,
      maxWidth: '100%',
    },
    ghostButtonDisabled: {
      opacity: 0.5,
    },
    ghostButtonCompact: {
      paddingVertical: 6,
      flexGrow: 0,
      alignSelf: 'flex-start',
    },
    ghostButtonAccent: {
      backgroundColor: colors.surfaceAlt9,
      borderColor: colors.borderAccent,
    },
    ghostButtonText: {
      color: colors.text,
      fontFamily: FONT_HEADING,
      fontSize: TYPO_SCALE.body,
      letterSpacing: LETTER_SPACING.heading,
      flexShrink: 1,
      flexWrap: 'wrap',
    },
    ghostButtonTextDisabled: {
      color: colors.textMuted,
    },
    logMeasurementButton: {
      borderColor: colors.success,
      backgroundColor: rgba.successSoftAlt || colors.surfaceAlt3,
    },
    logMeasurementButtonText: {
      color: colors.successText || colors.text,
    },
    logMeasurementButtonDisabled: {
      borderColor: colors.borderDisabled,
      backgroundColor: colors.surfaceAlt11,
      opacity: 0.6,
    },
    logMeasurementButtonTextDisabled: {
      color: colors.textMuted,
    },
    logRow: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      padding: 12,
      gap: 6,
      marginBottom: 8,
    },
    logName: {
      color: colors.text,
      fontFamily: FONT_HEADING,
      fontSize: TYPO_SCALE.body,
    },
    logValue: {
      color: colors.textMuted,
      fontFamily: FONT_BODY,
      fontSize: TYPO_SCALE.body,
    },
    logActions: {
      flexDirection: 'row',
      gap: 12,
    },
    logActionText: {
      color: colors.link,
      fontFamily: FONT_HEADING,
      fontSize: TYPO_SCALE.body,
    },
    modalInline: {
      marginTop: 12,
      padding: 12,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      backgroundColor: colors.surfaceAlt,
      gap: 10,
    },
    fieldRow: {
      gap: 6,
    },
    fieldGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    fieldColumn: {
      flexGrow: 1,
      flexBasis: 260,
      minWidth: 240,
      maxWidth: '48%',
    },
    fieldLabel: {
      color: colors.textMuted,
      fontFamily: FONT_BODY,
      fontSize: TYPO_SCALE.body,
    },
    pickerWrapper: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      overflow: 'hidden',
      backgroundColor: colors.surfaceAlt2,
    },
    pickerTrigger: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 10,
      backgroundColor: colors.surfaceAlt2,
    },
    pickerTriggerText: {
      color: colors.text,
      fontFamily: FONT_BODY,
      fontSize: TYPO_SCALE.body,
    },
    pickerTriggerIcon: {
      color: colors.accent,
      fontFamily: FONT_HEADING,
      fontSize: TYPO_SCALE.body,
    },
    pickerModal: {
      backgroundColor: colors.surface,
      borderRadius: 16,
      borderColor: colors.accent,
      borderWidth: 2,
      padding: 16,
      maxHeight: '70%',
      width: '100%',
      maxWidth: 520,
      alignSelf: 'center',
    },
    pickerList: {
      marginTop: 8,
    },
    pickerOption: {
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: 'transparent',
      backgroundColor: colors.surfaceAlt,
      marginBottom: 8,
    },
    pickerOptionActive: {
      borderColor: colors.accent,
      backgroundColor: colors.surfaceAlt10,
    },
    pickerOptionText: {
      color: colors.textSoft,
      fontFamily: FONT_BODY,
      fontSize: TYPO_SCALE.body,
    },
    pickerOptionTextActive: {
      color: colors.accent,
      fontFamily: FONT_HEADING,
      letterSpacing: LETTER_SPACING.heading,
    },
    picker: {
      color: colors.text,
      fontFamily: FONT_BODY,
      fontSize: TYPO_SCALE.body,
      backgroundColor: colors.surfaceAlt2,
    },
    pickerItem: {
      color: colors.text,
      fontFamily: FONT_BODY,
      fontSize: TYPO_SCALE.body,
    },
    numericControl: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      overflow: 'hidden',
      backgroundColor: colors.surfaceAlt2,
    },
    numericControlDisabled: {
      borderColor: colors.borderDisabled,
      backgroundColor: colors.surfaceAlt11,
      opacity: 0.7,
    },
    numericButton: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRightWidth: 1,
      borderRightColor: colors.border,
    },
    numericButtonDisabled: {
      opacity: 0.45,
    },
    numericButtonText: {
      color: colors.warning,
      fontFamily: FONT_HEADING,
      fontSize: TYPO_SCALE.body,
    },
    numericButtonTextDisabled: {
      color: colors.textMuted,
    },
    numericButtonSpacer: {
      width: 40,
      height: '100%',
    },
    numericInput: {
      flex: 1,
      paddingHorizontal: 8,
      paddingVertical: 6,
      color: colors.text,
      fontFamily: FONT_BODY,
      fontSize: TYPO_SCALE.body,
      textAlign: 'center',
    },
    numericInputDisabled: {
      color: colors.textMuted,
    },
    fieldLabelRef: {
      color: colors.info,
      fontFamily: FONT_HEADING,
      letterSpacing: LETTER_SPACING.heading,
    },
    segmentedRow: {
      flexDirection: 'row',
      gap: 8,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 4,
      backgroundColor: colors.surface,
    },
    segmentedButton: {
      flex: 1,
      borderRadius: 999,
      paddingVertical: 8,
      alignItems: 'center',
    },
    segmentedButtonActive: {
      backgroundColor: colors.accent,
    },
    segmentedText: {
      color: colors.textSubtle,
      fontFamily: FONT_HEADING,
      fontSize: TYPO_SCALE.body,
      textAlign: 'center',
      width: '100%',
    },
    segmentedTextActive: {
      color: colors.textOnAccent,
      textAlign: 'center',
      width: '100%',
    },
    chipButton: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 999,
      paddingHorizontal: 12,
      paddingVertical: 6,
      backgroundColor: colors.surfaceAlt8,
    },
    chipButtonActive: {
      backgroundColor: colors.accent,
      borderColor: colors.accent,
    },
    chipButtonText: {
      color: colors.textSubtle,
      fontFamily: FONT_HEADING,
      fontSize: TYPO_SCALE.body,
    },
    chipButtonTextActive: {
      color: colors.textOnAccent,
    },
    chipRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    metricRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    metricRowCentered: {
      justifyContent: 'center',
      alignItems: 'center',
    },
    fovPreviewWrap: {
      alignItems: 'center',
      gap: 6,
      paddingVertical: 6,
    },
    fovPreview: {
      width: 200,
      height: 120,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      backgroundColor: colors.surfaceAlt,
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
      overflow: 'hidden',
    },
    fovPreviewOrigin: {
      position: 'absolute',
      left: '50%',
      top: '50%',
    },
    fovPreviewLine: {
      position: 'absolute',
      height: 2,
      backgroundColor: colors.accent,
      borderRadius: 2,
    },
    fovPreviewDot: {
      position: 'absolute',
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.textMuted,
      transform: [{ translateX: -4 }, { translateY: -4 }],
    },
    fovPreviewLabel: {
      color: colors.text,
      fontFamily: FONT_HEADING,
      fontSize: TYPO_SCALE.body,
      letterSpacing: LETTER_SPACING.heading,
    },
    metricCard: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      padding: 12,
      backgroundColor: colors.surfaceAlt,
    },
    metricLabel: {
      color: colors.textMuted,
      fontFamily: FONT_BODY,
      fontSize: TYPO_SCALE.small,
    },
    metricValue: {
      color: colors.text,
      fontFamily: FONT_HEADING,
      fontSize: TYPO_SCALE.subheading,
    },
    metricSubValue: {
      color: colors.textMuted,
      fontFamily: FONT_BODY,
      fontSize: TYPO_SCALE.small,
    },
    colorSwatchCard: {
      minWidth: 170,
      flexGrow: 1,
      flexBasis: 220,
      alignItems: 'flex-start',
      gap: 6,
    },
    metricCardWide: {
      flexGrow: 1,
      flexBasis: 220,
      minWidth: 180,
    },
    colorSwatch: {
      width: 56,
      height: 28,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: rgba.borderSwatch,
    },
    contrastTarget: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      padding: 12,
      backgroundColor: colors.surfaceAlt,
    },
    contrastTargetLabel: {
      color: colors.textMuted,
      fontFamily: FONT_BODY,
      fontSize: TYPO_SCALE.body,
    },
    contrastTargetValue: {
      color: colors.text,
      fontFamily: FONT_HEADING,
      fontSize: TYPO_SCALE.subheading,
    },
    bandBar: {
      gap: 8,
    },
    bandOverlay: {
      position: 'relative',
    },
    bandRow: {
      flexDirection: 'row',
      alignItems: 'center',
      height: 18,
      borderRadius: 10,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceAlt,
      zIndex: 1,
    },
    bandSegment: {
      height: '100%',
    },
    bandPointers: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: -6,
      height: 30,
      zIndex: 2,
    },
    bandPointer: {
      position: 'absolute',
      width: 4,
      height: 28,
      borderRadius: 2,
      transform: [{ translateX: -1 }],
      borderWidth: 1,
      borderColor: colors.text,
      ...(Platform.OS === 'web'
        ? { boxShadow: `0 2px 6px ${rgba.shadow || 'rgba(0, 0, 0, 0.35)'}` }
        : {
            shadowColor: '#000',
            shadowOpacity: 0.35,
            shadowRadius: 4,
            shadowOffset: { width: 0, height: 1 },
          }),
    },
    bandPointerKey: {},
    bandPointerFill: {},
    bandPointerLabel: {
      position: 'absolute',
      top: -18,
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 6,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      transform: [{ translateX: -12 }],
    },
    bandPointerLabelText: {
      fontFamily: FONT_HEADING,
      fontSize: TYPO_SCALE.small,
      letterSpacing: LETTER_SPACING.heading,
    },
    bandMarkers: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    bandMarkerText: {
      fontFamily: FONT_HEADING,
      fontSize: TYPO_SCALE.small,
      color: colors.textSubtle,
    },
    panelWrap: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 16,
      padding: 12,
      backgroundColor: colors.surfaceAlt,
    },
    panelSection: {
      marginTop: 12,
    },
    panelTitle: {
      fontFamily: FONT_HEADING,
      fontSize: TYPO_SCALE.body,
      color: colors.accent,
      marginBottom: 8,
    },
    falseColorGuide: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      padding: 12,
      backgroundColor: colors.surfaceAlt,
      gap: 10,
    },
    guideTitle: {
      color: colors.accent,
      fontFamily: FONT_HEADING,
      fontSize: TYPO_SCALE.body,
      letterSpacing: LETTER_SPACING.heading,
    },
    guideRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    statusBannerSuccess: {
      marginTop: 8,
      borderWidth: 1,
      borderColor: colors.success,
      borderRadius: 12,
      paddingVertical: 8,
      paddingHorizontal: 12,
      backgroundColor: rgba.successSoft,
    },
    statusBannerText: {
      color: colors.successText,
      fontFamily: FONT_HEADING,
      fontSize: TYPO_SCALE.body,
      letterSpacing: LETTER_SPACING.heading,
    },
    statusBadgeSuccess: {
      alignSelf: 'flex-start',
      borderWidth: 1,
      borderColor: colors.success,
      backgroundColor: rgba.successSoftAlt,
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 4,
      marginBottom: 8,
    },
    statusBadgeNeutral: {
      alignSelf: 'flex-start',
      borderWidth: 1,
      borderColor: colors.borderStrong,
      backgroundColor: colors.surfaceAlt,
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 4,
      marginBottom: 8,
    },
    statusBadgeText: {
      color: colors.textSoft,
      fontFamily: FONT_HEADING,
      fontSize: TYPO_SCALE.small,
      letterSpacing: LETTER_SPACING.heading,
    },
    compactLabelRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      flexWrap: 'wrap',
      gap: 8,
    },
    compactPanel: {
      paddingVertical: 8,
      paddingHorizontal: 10,
      gap: 8,
    },
    compactField: {
      gap: 4,
    },
    compactInput: {
      paddingVertical: 6,
    },
    guideChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 6,
      backgroundColor: colors.surfaceAlt2,
    },
    guideSwatch: {
      width: 16,
      height: 16,
      borderRadius: 4,
      borderWidth: 1,
      borderColor: rgba.borderSwatch,
    },
    guideTextStack: {
      gap: 2,
    },
    guideLabel: {
      color: colors.textSoft,
      fontFamily: FONT_HEADING,
      fontSize: TYPO_SCALE.small,
      letterSpacing: LETTER_SPACING.heading,
    },
    guideValue: {
      color: colors.textMuted,
      fontFamily: FONT_BODY,
      fontSize: TYPO_SCALE.small,
    },

    nowBar: {
      marginHorizontal: 16,
      marginTop: 8,
      padding: 14,
      borderRadius: 14,
      borderWidth: 2,
      borderColor: colors.accent,
      backgroundColor: colors.surface,
      gap: 10,
    },
    nowBarCompact: {
      marginHorizontal: 12,
    },
    nowBarRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
      flexWrap: 'wrap',
    },
    nowBarTitle: {
      color: colors.accent,
      fontFamily: FONT_HEADING,
      fontSize: TYPO_SCALE.subheading,
      letterSpacing: LETTER_SPACING.heading,
    },
    nowBarStatus: {
      color: colors.info,
      fontFamily: FONT_BODY,
      fontSize: TYPO_SCALE.body,
    },
    nowBarSelectors: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
    },
    nowBarSelectorsCompact: {
      gap: 8,
    },
    nowBarSelect: {
      flex: 1,
      minWidth: 220,
    },
    dashboardGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
      marginHorizontal: 16,
      marginTop: 16,
      justifyContent: 'flex-start',
      alignItems: 'flex-start',
    },
    dashboardGridCompact: {
      marginHorizontal: 12,
      gap: 10,
    },
    dashboardCard: {
      flexGrow: 1,
      flexBasis: 220,
      minWidth: 200,
      maxWidth: '48%',
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      overflow: 'hidden',
    },
    dashboardCardSquare: {
      aspectRatio: 1,
      minHeight: 200,
    },
    dashboardCardCompact: {
      flexBasis: '100%',
      minWidth: '100%',
      maxWidth: '100%',
      minHeight: 120,
    },
    dashboardCardDisabled: {
      opacity: 0.65,
    },
    dashboardCardInner: {
      padding: 10,
      gap: 6,
    },
    dashboardCardInnerCompact: {
      padding: 10,
      gap: 6,
      justifyContent: 'flex-start',
    },
    dashboardCardHeader: {
      gap: 6,
    },
    dashboardCardHeaderCompact: {
      gap: 4,
    },
    dashboardCardTitle: {
      color: colors.text,
      fontFamily: FONT_HEADING,
      fontSize: TYPO_SCALE.body - 2,
      letterSpacing: LETTER_SPACING.heading,
      lineHeight: TYPO_SCALE.body + 2,
      flexShrink: 1,
    },
    dashboardCardTitleCompact: {
      fontSize: TYPO_SCALE.body - 3,
      lineHeight: TYPO_SCALE.body + 1,
    },
    dashboardCardSubtitle: {
      color: colors.textMuted,
      fontFamily: FONT_BODY,
      fontSize: TYPO_SCALE.body - 2,
      lineHeight: TYPO_SCALE.body + 1,
      flexShrink: 1,
    },
    dashboardCardSubtitleCompact: {
      fontSize: TYPO_SCALE.body - 3,
      lineHeight: TYPO_SCALE.body + 1,
    },
    dashboardPalette: {
      flexDirection: 'row',
      gap: 4,
    },
    dashboardPaletteCompact: {
      gap: 3,
    },
    dashboardPaletteSwatch: {
      flex: 1,
      height: 4,
      borderRadius: 3,
      borderWidth: 1,
      borderColor: rgba.borderShadow,
    },
    dashboardPaletteSwatchCompact: {
      height: 3,
      borderRadius: 2,
    },
    metricCardCompact: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      paddingHorizontal: 10,
      paddingVertical: 8,
      backgroundColor: colors.surfaceAlt2,
    },
    metricCardCompactCompact: {
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    metricLabelCompact: {
      color: colors.textMuted,
      fontFamily: FONT_BODY,
      fontSize: TYPO_SCALE.body - 1,
      lineHeight: TYPO_SCALE.body + 3,
    },
    metricValueCompact: {
      color: colors.text,
      fontFamily: FONT_HEADING,
      fontSize: TYPO_SCALE.subheading - 3,
      letterSpacing: LETTER_SPACING.heading,
      lineHeight: TYPO_SCALE.subheading + 2,
      flexShrink: 1,
      flexWrap: 'wrap',
    },
    metricValueCompactCompact: {
      fontSize: TYPO_SCALE.body,
      lineHeight: TYPO_SCALE.body + 2,
    },
    metricValueCompactSm: {
      fontSize: TYPO_SCALE.small,
      lineHeight: TYPO_SCALE.body,
    },
    roleSelectorGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
      justifyContent: 'space-between',
    },
    roleCard: {
      flexGrow: 1,
      flexBasis: 150,
      maxWidth: 210,
      minWidth: 130,
      borderWidth: 1,
      borderColor: colors.borderMuted,
      borderRadius: 12,
      backgroundColor: colors.surfaceAlt6,
      padding: 4,
      alignItems: 'center',
      justifyContent: 'space-between',
      aspectRatio: 1.2,
    },
    roleCardActive: {
      borderColor: colors.accent,
      backgroundColor: colors.surfaceAlt7,
      shadowColor: colors.accent,
      shadowOpacity: 0.3,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 4 },
      transform: [{ scale: 1.02 }],
    },
    roleCardAccent: {
      width: '100%',
      height: 3,
      borderRadius: 8,
      marginBottom: 2,
    },
    roleCardImageWrap: {
      flex: 1,
      width: '100%',
      alignItems: 'center',
      justifyContent: 'center',
    },
    roleCardImage: {
      width: '96%',
      height: '96%',
    },
    roleCardFooter: {
      gap: 0,
      alignItems: 'center',
    },
    roleCardLabel: {
      fontFamily: FONT_HEADING,
      fontSize: TYPO_SCALE.body - 2,
      color: colors.text,
      letterSpacing: LETTER_SPACING.heading,
      textAlign: 'center',
    },
    roleCardLabelActive: {
      color: colors.accent,
    },
    roleCardBadge: {
      fontFamily: FONT_BODY,
      fontSize: TYPO_SCALE.small,
      color: colors.success,
    },
    roleSelectorCardHeader: {
      paddingVertical: 8,
    },
    roleSelectorCardBody: {
      paddingVertical: 8,
      paddingHorizontal: 10,
    },
    statusBadgeColor: {
      alignSelf: 'flex-start',
      borderWidth: 1,
      borderColor: colors.success,
      backgroundColor: rgba.successSoftAlt,
      borderRadius: 999,
      paddingHorizontal: 9,
      paddingVertical: 3,
      marginBottom: 6,
    },
    statusBadgeWarn: {
      alignSelf: 'flex-start',
      borderWidth: 1,
      borderColor: colors.accent,
      backgroundColor: rgba.accentSoft,
      borderRadius: 999,
      paddingHorizontal: 9,
      paddingVertical: 3,
      marginBottom: 6,
    },
    statusBadgeWarnText: {
      color: colors.warningTextSoft,
      fontFamily: FONT_HEADING,
      fontSize: TYPO_SCALE.small,
      letterSpacing: LETTER_SPACING.heading,
    },
    entityActionBtnDanger: {
      borderColor: colors.danger,
      backgroundColor: rgba.dangerSoft,
    },
    entityActionTextDanger: {
      color: colors.dangerText,
    },
    entityActionBtnRename: {
      borderColor: colors.warning,
      backgroundColor: rgba.warningSoft,
    },
    entityActionTextRename: {
      color: colors.warningText,
    },
    entityActionBtnCreate: {
      borderColor: colors.success,
      backgroundColor: rgba.successSoftAlt,
    },
    entityActionTextCreate: {
      color: colors.successText,
    },
    entityActionBtnDuplicate: {
      borderColor: colors.magenta,
      backgroundColor: rgba.magentaSoft,
    },
    entityActionTextDuplicate: {
      color: colors.magentaText,
    },
    entityActionBtnDisabled: {
      opacity: 0.45,
    },
    entityActionTextDisabled: {
      color: colors.textMuted,
    },

    actionRow: {
      marginTop: 10,
      alignItems: 'flex-start',
      gap: 8,
    },
    actionPrimary: {
      borderWidth: 1,
      borderColor: colors.accent,
      backgroundColor: rgba.accentSoftAlt,
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 8,
    },
    actionPrimaryText: {
      color: colors.accent,
      fontFamily: FONT_HEADING,
      fontSize: TYPO_SCALE.body,
      letterSpacing: LETTER_SPACING.heading,
    },
    actionPrimaryDisabled: {
      opacity: 0.5,
    },
    actionPrimaryDisabledText: {
      color: colors.textMuted,
    },
  });
};

export { createAppStyles };
